
default: &default
  adapter: postgresql
  encoding: unicode
  username: recipe_app
  password: 123456789
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: strut_furniture_development
test:
  <<: *default
  database: strut_furniture_test
production:
  <<: *default
  database: strut_furniture_production
  username: deploy
  password: Rails.application.credentials.dig(:production, :db_password)
